::install
curl -Lo- https://bit.ly/janus-bootstrap | bash
::install_darwin
brew install ctags-exuberant
::install_ubuntu
sudo apt-get install exuberant-ctags
::unlink
rm .vimrc.after
rm .janus
::link
ln -s environment_setup/settings/vim/vimrc.after ~/.vimrc.after
ln -s environment_setup/settings/vim/janus ~/.janus
::reindex
ctags -f $ENV_SETUP/settings/vim/gemtags -R --exclude=.git --exclude=log $(rvm gemdir)
